const propositions = new Map([
    ["C1.1", "Développer puis mettre en place un score carbone sur tous les produits de consommation et les services."],
    ["C1.2", "Rendre obligatoire l'affichage des émissions de gaz à effet de serre dans les commerces et lieux de consommation ainsi que dans les publicités pour les marques."],
    ["C2.1", "Interdire de manière efficace et opérante la publicité des produits les plus émetteurs de GES, sur tous les supports publicitaires."],
    ["C2.2", "Réguler la publicité pour limiter fortement les incitations quotidiennes et non-choisies à la consommation."],
    ["C2.3", "Mettre en place des mentions pour inciter à moins consommer."],
    ["C3.1", "Mettre en place progressivement une obligation de l'implantation du vrac dans tous les magasins et l'imposition d'un pourcentage aux centrales d'achat."],
    ["C3.2", "Mise en place progressive d'un système de consigne de verre (lavable et réutilisable) jusqu'à une mise en place généralisée en 2025."],
    ["C3.3", "Favoriser le développement les emballages biosourcés compostables pour assurer la transition avant la fin de l'emballage plastique à usage unique."],
    ["C3.4", "Remplacer une part significative de la Taxe d'Enlèvement des Ordures Ménagères (TEOM) par des modalités plus justes et favorisant les comportements écoresponsables."],
    ["C5.1", "Modifier le code de l'éducation pour une généralisation de l'éducation à l'environnement et au développement durable (EEDD) dans le modèle scolaire français."],
    ["C5.2", "Renforcer les modalités d'éducation à l'environnement et au développement durable en en faisant une mission transversale des enseignants."],
    ["C5.3", "Sensibiliser l'ensemble de la population française en reliant compréhension de l'urgence climatique et passage à l'action."],
    ["C6.1", "Contrôler et sanctionner plus efficacement et rapidement les atteintes aux règles en matière environnementale."],
    ["C6.2", "Renforcer et centraliser l'évaluation et le suivi des politiques publiques en matière environnementale."],
    ["PT1.1", "Conception : Augmenter la longévité des produits et réduire la pollution."],
    ["PT1.2", "Faire respecter la loi sur l'interdiction de l'obsolescence programmée."],
    ["PT1.3", "Rendre obligatoire la possibilité de réparation des produits manufacturés qui sont vendus en France (1), la disponibilité des pièces détachées d'origine pendant une durée définie (2). Mettre en place et à proximité des filières et ateliers de réparation, et rendre accessibles les services après-vente (3)."],
    ["PT1.4", "Rendre obligatoire le recyclage de tous les objets en plastique dès 2023, supprimer tous les plastiques à usage unique dès 2023 et développer le recyclage des autres matières."],
    ["PT1.5", "Durcir et appliquer la réglementation sur la gestion des déchets."],
    ["PT2.1", "D'ici 2025 tout soutien à l'innovation doit s'inscrire dans une logique de sortie d'un modèle basé sur le carbone."],
    ["PT3.1", "Réglementer l'utilisation de l'épargne réglementée gérée par la Caisse des Dépôts et Consignations (CDC) et les banques pour financer des investissements verts - Faire évoluer la gouvernance de la CDC pour soutenir cette logique."],
    ["PT3.2", "Les entreprises qui distribuent plus de 10 millions d'euros de dividendes annuels, participeront, chaque année, à l'effort de financement à la hauteur de 4 % et celles dont les dividendes sont inférieurs ou égaux à 10 millions d'€ participeront à hauteur de 2 %."],
    ["PT3.3", "Mettre en place les modalités de financement par loi ou décret avec un emprunt d'État dédié au financement de la transformation des entreprises."],
    ["PT4.1", "Accompagner les salariés et les entreprises dans la transition."],
    ["PT4.2", "Créer une nouvelle gouvernance de la transition des emplois et compétences au niveau national et régional."],
    ["PT6.1", "Annualiser le reporting et l'étendre à toutes les organisations champ d'émissions au scope 3 - Sanction pour non-réalisation en % du chiffre d'affaire."],
    ["PT6.2", "Élargir le périmètre de reporting au secteur financier - Renforcer les obligations de rapportage au secteur de la finance."],
    ["PT6.3", "Bonus pour les entreprises ayant une évolution positive - Conditionner les aides publiques à l'évolution positive du bilan gaz à effet de serre."],
    ["PT7.1", "Renforcer les clauses environnementales dans les marchés publics."],
    ["PT8.1", "Protection des écosystèmes et de la biodiversité."],
    ["PT8.2", "Traiter la «nocivité» — OGM et principe de précaution — prévention."],
    ["PT8.3", "Traitement des déchets et des produits."],
    ["PT8.4", "Traitement des eaux."],
    ["PT8.5", "Exploitation et gestion des forêts."],
    ["PT8.6", "Moratoire sur l'exploitation industrielle minière en Guyane."],
    ["PT8.7", "Prévention des espaces aquatiques et modification de leur exploitation."],
    ["PT9.1", "Ajustement carbone aux frontières de l'UE (en fonction de l'empreinte carbone) et prise en compte les enjeux de redistribution pour éviter de peser sur les ménages les moins favorisés."],
    ["PT11.1", "Amélioration de la gouvernance territoriale/régionale."],
    ["PT11.2", "Participation des citoyens, entreprises locales, associations locales et collectivités locales aux projets énergies renouvelables (EnR)."],
    ["PT11.3", "Développement de l'autoconsommation."],
    ["PT12.1", "Accompagner l'évolution du numérique pour réduire ses impacts environnementaux."],
    ["SD-A1.1", "Inciter à utiliser des moyens de transports doux ou partagés, notamment pour les trajets domicile-travail, en généralisant et en améliorant le forfait mobilité durable, prévue par la récente loi d'orientation des mobilités."],
    ["SD-A1.2", "Réduire les incitations à l'utilisation de la voiture en réformant le système d'indemnité kilométrique de l'impôt sur le revenu."],
    ["SD-A1.3", "Inciter à utiliser des moyens de transports doux ou partagés."],
    ["SD-A2.1", "Créer des parkings relais."],
    ["SD-A2.2", "Interdire les centres villes pour les véhicules les plus émetteurs de gaz à effet de serre."],
    ["SD-A2.3", "Augmenter les montants du Fonds Vélo de 50 à 200 millions d'euros par an pour financer des pistes cyclables."],
    ["SD-A2.4", "Généraliser les aménagements de voies réservées aux véhicules partagés et aux transports collectifs sur les autoroutes et voies rapides."],
    ["SD-A3.1", "Réduire la vitesse sur autoroute à 110 km/h maximum."],
    ["SD-A4.1", "Réduire la TVA sur les billets de train de 10 % à 5,5 %."],
    ["SD-A4.2", "Généraliser les mesures tarifaires attractives déjà pratiquées par certaines régions."],
    ["SD-A4.3", "Développer un plan d'investissement massif pour moderniser les infrastructures, les matériels roulants et les gares pour en faire des pôles multimodaux (lien avec les voitures, cars, vélos…)."],
    ["SD-B1.1", "Développer les autoroutes de fret maritime (et fluvial), sur des trajets déterminés."],
    ["SD-B1.2", "Imposer un suivi régulier de la formation des chauffeurs à l'écoconduite."],
    ["SD-B1.3", "Imposer aux constructeurs de poids lourds d'adopter la même filière énergétique dans leur recherche et développement."],
    ["SD-B1.4", "Sortir progressivement des avantages fiscaux sur le gazole, en échange de compensations fortes pour les transporteurs sous forme d'aides au financement accrues pour l'achat de poids-lourds neufs plus propres en remplacement des poids lourds polluants."],
    ["SD-B1.5", "Inciter, par des obligations réglementaires et fiscales, au report partiel vers d'autres moyens de transport de marchandises moins émetteurs."],
    ["SD-B1.6", "Obliger les chargeurs à intégrer des clauses environnementales."],
    ["SD-B1.7", "Favoriser le transport de marchandises sur des circuits courts par une modulation de la TVA."],
    ["SD-B2.1", "Interdire l'usage des moteurs polluants lors des arrêts dans les ports."],
    ["SD-B2.2", "Mettre à disposition les moyens d'alimenter en électricité les navires à quai pour permettre une réduction des émissions liées à l'usage des moteurs."],
    ["SD-B2.3", "Agir sur la réglementation internationale pour encadrer les émissions des gaz à effet de serre des navires."],
    ["SD-C1.1", "Augmenter le bonus pour les véhicules peu polluants, afin d'aider davantage les ménages et les professionnels dans leur évolution."],
    ["SD-C1.2", "Renforcer très fortement le malus sur les véhicules polluants et introduire le poids comme un des critères à prendre en compte."],
    ["SD-C1.3", "Interdire dès 2025 la commercialisation de véhicules neufs très émetteurs ; les véhicules anciens pouvant continuer de circuler."],
    ["SD-C1.4", "Moduler les taxes sur les contrats d'assurance en fonction de l'émission de CO2 pour encourager les véhicules propres."],
    ["SD-C1.5", "Permettre l'accès à des véhicules propres en développant la location de longue durée."],
    ["SD-C1.6", "Proposer des prêts à taux zéro, avec la garantie de l'État, pour l'achat d'un véhicule peu émetteur (léger et pas trop cher)."],
    ["SD-C1.7", "Créer des vignettes vertes à positionner sur les plaques d'immatriculation pour les véhicules les plus propres et donnant accès à des services particuliers : accès au centre-ville, places de parking, etc."],
    ["SD-C1.8", "Prévoir un plan de formation pour les garagistes, et plus largement de la filière «pétrole», pour accompagner la transformation progressive du parc automobile (nouveaux moteurs, carburants, systèmes)."],
    ["SD-D1.1", "Renforcer les plans de mobilité en les rendant obligatoires pour toutes les entreprises et toutes les collectivités."],
    ["SD-D1.2", "Les Autorités organisatrices de la mobilité (AOM) peuvent aider à mettre en place ces plans de mobilité en accompagnant les entreprises."],
    ["SD-D1.3", "Favoriser les plans interentreprises et intra-entreprise (covoiturage, ramassage des salariés en bus, vélo …) dans le cadre des plans de mobilité."],
    ["SD-D1.4", "Favoriser des nouvelles modalités d'organisation du travail."],
    ["SD-D2.1", "Mettre en place un portail unique permettant de savoir à tout moment, rapidement et simplement, quels sont les moyens et dispositifs existants sur un territoire pour se déplacer."],
    ["SD-D2.2", "Développer un projet d'unification des titres de transport ou de carte multimodale."],
    ["SD-D3.1", "Intégrer les citoyens aux Autorités organisatrices de la mobilité à toutes les échelles."],
    ["SD-E1", "Adopter une écocontribution kilométrique renforcé."],
    ["SD-E2", "Organiser progressivement la fin du trafic aérien sur les vols intérieurs d'ici 2025, uniquement sur les lignes où il existe une alternative bas carbone satisfaisante en prix et en temps (sur un trajet de moins de 4h)."],
    ["SD-E3", "Interdire la construction de nouveaux aéroports et l'extension des aéroports existants."],
    ["SD-E4", "Taxer davantage le carburant pour l'aviation de loisir."],
    ["SD-E5", "Promouvoir l'idée d'une écocontribution européenne."],
    ["SD-E6", "Garantir que l'ensemble des émissions qui ne pourraient être éliminées soient intégralement compensées par des puits de carbone."],
    ["SD-E7", "Soutenir, à moyen terme, la R&D dans le développement d'une filière biocarburants pour les avions."],
    ["SL1.1", "Contraindre les propriétaires occupants et bailleurs à rénover de manière globale."],
    ["SL1.2", "Obliger le changement des chaudières au fioul et à charbon d'ici à 2030 dans les bâtiments neufs et rénovés."],
    ["SL1.3", "Déployer un réseau harmonisé de guichets uniques."],
    ["SL1.4", "Système progressif d'aides à la rénovation, avec prêts et subventions pour les plus démunis."],
    ["SL1.5", "Former les professionnels du bâtiment pour répondre à la demande de rénovation globale et assurer une transition de tous les corps de métiers du BTP vers des pratiques écoresponsables."],
    ["SL2.1", "Contraindre par des mesures fortes les espaces publics et les bâtiments tertiaires à réduire leur consommation d'énergie."],
    ["SL2.2", "Changer en profondeur les comportements en incitant les particuliers à réduire leur consommation d'énergie."],
    ["SL2.3", "Inciter à limiter le recours au chauffage et à la climatisation dans les logements, les espaces publics et ceux ouverts au public ainsi que les bâtiments tertiaires (température moyenne maximale de 19°, renoncer à la climatisation en deçà de 30°)."],
    ["SL3.1", "Définir une enveloppe restrictive du nombre d'hectares maximum pouvant être artificialisés réduisant par 2 l'artificialisation des sols et rendre les PLUI1 et PLU2 conformes aux SCoT3 (et non plus compatibles)."],
    ["SL3.2", "Interdire toute artificialisation des terres tant que des réhabilitations ou friches commerciales, artisanales ou industrielles sont possibles dans l'enveloppe urbaine existante."],
    ["SL3.3", "Prendre immédiatement des mesures coercitives pour stopper les aménagements de zones commerciales périurbaines très consommatrices d'espace."],
    ["SL3.4", "Protéger fermement et définitivement les espaces naturels, les espaces agricoles périurbains et les forêts périurbaines. S'assurer d'une gestion durable de l'ensemble des forêts privées et publiques. S'assurer de la création de ceintures maraichères autour des pôles."],
    ["SL3.5", "Faciliter les changements d'usage des terrains artificialisés non occupés."],
    ["SL3.6", "Faciliter les réquisitions de logements et bureaux vacants."],
    ["SL3.7", "Faciliter les reprises et réhabilitations des friches, notamment par la possibilité pour les communes d'exproprier les friches délaissées depuis 10 ans ou plus."],
    ["SL3.8", "Évaluer le potentiel de réversibilité des bâtiments avant toute démolition."],
    ["SL3.9", "Permettre la construction d'immeubles collectifs dans les zones pavillonnaires 1. Plan local d'urbanisme intercommunal 2. Plan local d'urbanisme 3. Schéma de cohérence territoriale."],
    ["SL3.10", "Renforcer les contrôles du respect des obligations de protection des espaces et de limitation de consommation des terres non urbanisés, sanctionner pénalement les manquements."],
    ["SL3.11", "Sensibiliser à l’importance et l’intérêt de la ville plus compacte, et construire une nouvelle culture de l’habitat collectif."],
    ["SL3.12", "Financer les rénovations des logements dans les petites communes."],
    ["SL3.13", "Rendre les centres plus attractifs par la revitalisation des commerces et le maintien des écoles en milieu rural."],
    ["SN1.1.1", "Mettre en place une prime à l'investissement pour les établissements leur permettant de s'équiper en matériel, de former les personnels, de mener des campagnes de sensibilisation afin d'atteindre les objectifs de la loi EGalim."],
    ["SN1.1.2", "Proposer un bonus de 10 cts par repas pour les petites cantines bio et locales (moins de 200 repas par jour) pour les aider à absorber le surcoût les 3 premières années de leur transition."],
    ["SN1.1.3", "Créer un «observatoire de la restauration collective» ayant pour objectif de partager les bonnes pratiques et de suivre l'atteinte des objectifs de la loi EGalim."],
    ["SN1.1.4", "Mettre en place un organisme de contrôle pour assurer la bonne mise en œuvre de la loi EGalim."],
    ["SN1.1.5", "Encourager la réflexion pour réécrire l'arrêté du 30 septembre 2011 relatif à la qualité nutritionnelle des repas servis en restauration scolaire."],
    ["SN1.1.6", "Passer à un choix végétarien quotidien dans la restauration collective publique à partir de 2022 y compris dans la restauration collective à menu unique."],
    ["SN1.1.7", "Étendre toutes les dispositions de la loi EGalim à la restauration collective privée à partir de 2025."],
    ["SN1.1.8", "Étendre la liste des produits éligibles aux 50 % définis par la loi aux agriculteurs en transition vers le bio, et aux produits à faible coût environnemental."],
    ["SN1.1.9", "Aider à la structuration des filières afin qu’elles arrivent à faire reconnaître des produits dans des signes de qualité."],
    ["SN1.2.1", "Assurer la présence de la Direction générale de la concurrence, de la consommation et de la répression des fraudes (DGCCRF) dans les négociations, rendre la méthode obligatoire pour toutes les filières et organiser des rendez-vous réguliers à l'échelle des interprofessions, obliger à la transparence, les entreprises agroalimentaires et les centrales d'achats."],
    ["SN1.3.1", "Utiliser le levier de la commande publique pour valoriser les produits issus de circuits courts, locaux et à faible coût environnemental, sous la forme d'un «guide d'achat» à adresser aux acheteurs publics."],
    ["SN1.4.1", "Poursuivre les efforts dans la restauration collective."],
    ["SN2.1.1", "Atteindre 50 % d'exploitations en agroécologies en 2040."],
    ["SN2.1.2", "Inscription dans la loi et le PSN : Développer l'agriculture biologique (maintenir l'aide à la conversion, restaurer l'aide au maintien de l'agriculture biologique, faire supporter le coût de certification annuelle du label par l'État)."],
    ["SN2.1.3", "Engrais azotés : Augmenter la Taxe Générale sur les Activités Polluantes (TGAP)."],
    ["SN2.1.4", "Diminution de l'usage des pesticides avec une interdiction des produits CMR, diminution de l'usage des produits phytopharmaceutiques de 50 % d'ici 2025 et interdiction des pesticides les plus dommageable pour l'environnement en 2035."],
    ["SN2.1.5", "Inscription dans la loi et le PSN : Aider à la structuration de la filière des protéagineux (augmentation de l'autonomie du cheptel animal français, 100 % d'autonomie pour l'alimentation humaine en protéines végétales, accroissement de la diversification des cultures dans la PAC, mise en œuvre du Plan Protéines Végétales national)."],
    ["SN2.1.6", "Inscription dans la loi et le PSN : Aider au maintien des prairies permanentes (éviter au maximum les terres nues en mettant en place un couvert végétal obligatoire, rémunérer les services rendus par les agriculteurs pour le stockage de carbone par leurs activités)."],
    ["SN2.1.7", "Inscription dans la loi et le PSN : Interdire le financement d'implantation de nouveaux élevages qui ne respectent pas les conditions d'agroécologie et de faibles émissions de gaz à effet de serre, accompagner les éleveurs vers une restructuration de leurs cheptels pour améliorer la qualité de production Les propositions de la Convention Citoyenne pour le Climat."],
    ["SN2.2.1", "Réformer l'enseignement et la formation agricole : intégrer au tronc commun obligatoire l'enseignement de l'agroécologie, imposer des stages dans des exploitations qui appliquent les méthodes de l'agroécologie, ouvrir la formation continue sur les pratiques agroécologiques pour tous les agriculteurs, former les conseillers techniques aux pratiques de l'agroécologie."],
    ["SN2.3.1", "Relever les niveaux d'exigences des conditions de verdissement."],
    ["SN2.3.2", "Transformer l'attribution des aides à l'hectare vers des aides à l'actif agricole."],
    ["SN2.4.1", "Mettre en place un mécanisme de suivi et d'évaluation de l'atteinte de la performance climat du Plan Stratégique National (PSN)."],
    ["SN2.4.2", "Mettre en compatibilité le Plan Stratégique National (PSN) avec la Stratégie Nationale Bas Carbone (SNBC), la Stratégie Nationale pour la Biodiversité, le Plan National Santé Environnement, la Stratégie Nationale de lutte contre la Déforestation Importée (SNDI)."],
    ["SN2.4.3", "Intégrer toutes les dispositions concernant le développement de l'agroécologie au Plan Stratégique National (PSN)."],
    ["SN3.1.1", "Améliorer la connaissance des stocks/déplacements de poissons pour mieux définir les quotas et éliminer la surpêche."],
    ["SN3.1.2", "Poursuivre les efforts de limitation de la pêche dans les zones et pour les stocks fragiles, et affermir les contrôles sur l'interdiction de la pêche en eau profonde."],
    ["SN3.1.3", "Développer les fermes aquacoles raisonnées et respectueuses de l'environnement, afin d'éviter de pêcher les poissons dans leur milieu naturel."],
    ["SN3.1.4", "Protéger la capacité des océans à stocker du carbone, notamment en protégeant les baleines et les espèces marines."],
    ["SN3.1.5", "Diminuer les émissions de gaz à effet de serre dues à la pêche et au transport maritime en poursuivant la modernisation de la flotte de bateaux vers des systèmes de propulsion vert."],
    ["SN4.1.1", "Renégocier le CETA (Comprehensive Economic and Trade Agreement) au niveau européen pour y intégrer les objectifs climatiques de l'accord de Paris."],
    ["SN4.1.2", "Demander au gouvernement français de défendre une réforme politique commerciale européenne : inscrire le principe de précaution dans les accords commerciaux, inscrire le respect des engagements de l'accord de Paris comme objectifs contraignants, mettre fin aux tribunaux d'arbitrage privés, garantir la transparence et permettre le contrôle démocratique des négociations."],
    ["SN4.1.3", "Demander au gouvernement français de défendre des positions auprès de l'OMC : prendre en considération les accords de Paris dans les négociations commerciales, mise en place de sanctions pour les États récalcitrants, inclure les clauses environnementales dans les négociations d'accords commerciaux."],
    ["SN5.2.1", "Mieux informer le consommateur en renforçant la communication autour du PNNS et réformer le PNNS en PNNSC."],
    ["SN5.2.2", "Interdire la publicité sur les produits proscrits par le PNNS."],
    ["SN5.2.3", "Concevoir une nouvelle solidarité nationale alimentaire pour permettre aux ménages modestes d'avoir accès à une alimentation durable."],
    ["SN5.3.1", "Réformer le fonctionnement des labels en supprimant les labels privés et en mettant en place un label pour les produits issus de l'agriculture agro écologique."],
    ["SN6.1.1", "Informer les consommateurs du degré de transformation des produits, notamment via un étiquetage obligatoire et la mise en place d'une charte éthique agroalimentaire qui renseigne et qualifie en termes de gaz à effet de serre les auxiliaires techniques et les additifs alimentaires. Informer rapidement et manière obligatoire sur les accidents alimentaires."],
    ["SN6.1.2", "Interdire l'importation des produits qui sont composés d'auxiliaires technologiques proscrits par l'Union européenne."],
    ["SN6.1.3", "Interdire progressivement l'usage des auxiliaires de production et des additifs alimentaires sous 5 ans."],
    ["SN6.1.4", "Taxer les produits-ultra transformés à forte empreinte carbone et faible apport nutritionnel."],
    ["SN6.1.5", "Mettre en place de chèques alimentaires pour les plus démunis à utiliser dans les AMAP (Association pour le Maintien d'une Agriculture Paysanne) ou pour des produits bios."],
    ["SN7.1", "Adopter une loi qui pénalise le crime d'écocide dans le cadre des 9 limites planétaires, et qui intègre le devoir de vigilance et le délit d'imprudence, dont la mise en œuvre est garantie par la Haute Autorité des Limites Planétaires."],
    ["RC1", "Renforcer le contrôle des politiques environnementales, en créant, notamment un «Défenseur de l’environnement» à l'image du Défenseur des droits."],
    ["RC2", "Réforme du Conseil Économique, Social et Environnemental."],
    ["RC3", "Modifier le préambule de la Constitution pour y ajouter : « « La conciliation des droits, libertés et principes qui en résultent ne saurait compromettre la préservation de l'environnement, patrimoine commun de l'humanité. »"],
    ["RC4", "Modifier l'article premier de la Constitution pour y ajouter : « La République garantit la préservation de la biodiversité, de l'environnement et lutte contre le dérèglement climatique »."]
]);