[build]
  base = "/"
  publish = "/public"
  command = "npm i -g node-sass && node-sass ./src/scss/style.scss -o ./src/css --style compressed && mkdir ./public && cp -R ./src/{js,css,index.html} ./public"
